name:                yaar
version:             0.1.0.0
bitbucket:              "sras/yaar"
license:             BSD3
author:              "Sandeep.C.R"
maintainer:          "sandeepcr2@gmail.com"
copyright:           "2018 Sandeep.C.R"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        ""

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- wai
- http-types
- containers
- aeson

library:
  source-dirs: src

tests:
  yaar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaar
